# Generated by Django 4.2.1 on 2023-06-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='currentExp',
            new_name='current_exp',
        ),
    ]
